### PR TITLE
docs: Update model user tutorial links

### PR DESCRIPTION
**Pull request by ckadner**
image

https://caikit.github.io/website/website/docs/tutorial_appdev.html

image

---

Similarly, the link at the bottom of the "Key concepts" page:

image

--> `404`

### CODE REVIEW

**Review by dmuelle — APPROVED** [review]

**Comment by ronensc** [comment]
Although the PR has already been merged, it appears that the link is still broken on the website.
https://caikit.github.io/website/

**Comment by dmuelle** [comment]
Thanks @ronensc - we had a strange issue with the link path but it is now resolved and the tutorial link works from both locations. Thanks for your help!

**Comment by ronensc** [comment]
I verify that the issue is resolved.
But, I now noticed that the link to `Development Guide`  in the ["Contributing to Caikit"](https://caikit.github.io/website/docs/contributing.html) page is also broken.

**Comment by dmuelle** [comment]
Thanks @ronensc - this is now fixed by #30 . I've also gone through each page on the site and manualy checked all the links. I believe everything is working now.

**Pull request merged**
